application: ovivogae
version: b02
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /sitemap.xml
  script: sitemap.application

- url: /vikarbureau/.*
  script: vikar.application

- url: /review
  script: review.application

- url: /.*
  script: index.application
